### numpy 명령어

In [1]:
import numpy as np

### 넘파이 배열

In [2]:
# 1차원 배열 만들기 numpy.array([]): - 배열 정의 행렬형태의 데이터를 가져옴
a=np.array([1,2,3,4,5])
a
# 자료형은 리스트가 아닌 ndarray로 나타남 - type으로 확인가능
# 2차원 배열 만들기
c=np.array([[0,1,2],[3,4,5]]) # - 2x3 array
print(c)
print(len(c)) # row 개수
print(len(c[0])) # col 개수

[[0 1 2]
 [3 4 5]]
2
3


In [3]:
# 벡터화 연산 - 빠르게 계산가능
data=[0,1,2,3,4,5,6,7,8,9]
x=np.array(data)
2*x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
# 배열의 차원과 크기 알아내기
a=np.array([1,2,3])
print(a.ndim) # 배열의 차원 반환
print(a.shape) # 배열의 크기 반환

# 배열의 인덱싱 - 리스트와 동일
b = np.array([[0, 1, 2], [3, 4, 5]])
b[-1,-1]
# 배열 슬라이싱
b[0,:]

1
(3,)


array([0, 1, 2])

In [5]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
idx=[x%3==0]
adx=[x%4==1]
z=x[idx]
edx=[z%4==1]
z[edx]

C:\Users\user\AppData\Local\Temp\ipykernel_19404\1071862671.py:5: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  z=x[idx]
C:\Users\user\AppData\Local\Temp\ipykernel_19404\1071862671.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  z[edx]


array([9])

### 배열의 생성과 변형

In [6]:
# np의 자료형 - 모두 같은 자료형인 원소로 구성되어야 함 dtype으로 자료형 확인
x = np.array([1, 2, 3])
y = np.array([1.0, 2.0, 3.0])
z = np.array([1, 2, 3.0])
x.dtype
y.dtype
z.dtype
# dtype 지정
# b - t or f, i 정수, u 부호없는 정수, f 부동소수점, c 복소 부동소수점, o 객체
# i8, u8, f8 = 64bit
q = np.array([1,2,3,4],dtype='i')
q.dtype

dtype('int32')

In [7]:
# Inf(무한) 와 NaN(정의 불가 수)
# 배열 생성
# np.zeros(m, n) m x n 크기의 성분이 전부 0인 행렬생성
a = np.zeros(5)
a
b= np.zeros((2,3)) # 다차원 배열 형성시
b
# np.ones(m, n) 0 대신 1 들어감
e=np.ones((2,3,4)) # 3x4 배열 2개 형성
e
# 크기를 명시하지 않고 다른 배열과 같은 크기로 만들시
f=np.ones_like(b) # zeros 도 된다
f
# numpy.empty((m, n)) 빈 m,n 크기의 행렬 생성
# np.arange() 리스트랑 같은 방법
c=np.arange(1,10,2)
c
# np.linspace(시작, 끝(포함), 갯수) - 구간 분할
d=np.linspace(0,100,5)
d
# np.logspace 로그 구간 분할
g=np.logspace(0.1,1,10)
g

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [8]:
# 전치 연산
A=np.array([[1,2,3,],[4,5,6]])
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [45]:
# 배열 크기 변형
a=np.arange(12)
a
a.reshape(3,4) # 값 중 하나는 -1로 작성 가능 - 자동으로 계산되어 적용됨
a.reshape(2,2,-1)

# 다차원 배열 1차원으로 만들기
a.flatten() # or a.ravel()
#   여기서 정렬방식에 따라 A.flatten(order='?') 로 표현가능
#   ? = C or F or A(A는 몰라도됨)
#   C인 경우는 기본설정으로 row기준으로 배열(행벡터화)
#   F인 경우는 column을 기준으로 배열(열벡터화) 

# 차원만 증가시키기
x= np.arange(6)
x.reshape(1,-1)
x[:,np.newaxis]



array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [10]:
# 배열 연결
# 열 연결 - row 수 같아야함
a1=np.ones((2,3))
a2=np.zeros((2,2))
np.hstack([a1,a2])
np.r_[np.array([1,2,3]),np.array([4,5,6])]
# 행 연결 - col 수 같아야함
b1=np.ones((2,3))
b2=np.zeros((3,3))
np.vstack([b1,b2])
# 1차원 행을 열로 변환 후 열 연결
np.c_[np.array([1,2,3]),np.array([4,5,6])]
# 깊이 배열 합 - 행열 다 같아야함?
c1=np.ones((3,4))
c2=np.zeros((3,4))
c=np.dstack([c1,c2])
c.shape
c3=np.stack([c1,c2],axis=1)
c3
# 동일한 배열 반복 연결
a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a,(3,2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [11]:
# 연습문제
a1=np.zeros((3,3))
a2=np.ones((3,2))
a=np.hstack([a1,a2])
b1=np.arange(10,160,10)
b=b1.reshape(3,-1)
c1=np.vstack([a,b])
d=np.tile(c1,(2,1))
d

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [54]:
# 2차원 그리드 포인트 생성 - 변수가 2개인 2차원 함수의 그래프
x=np.arange(3)
y=np.arange(5)
X,Y=np.meshgrid(x,y)
z=[list(zip(x,y)) for x,y in zip(X,Y)]; z

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [13]:
# numpy.full((m, n), k) m x n 크기의 성분이 전부 k인 행렬생성
# numpy.eye(n)  n차 단위행렬(I) 생성

### 배열의 연산

In [14]:
# 벡터화 연산 - 덧셈
x=np.arange(1,10001)
y=np.arange(10001,20001)
z=x+y
z[:10]
#   그냥 A, B로 행렬 지정 후 A+B 해도 됨
# - 곱셈은 스칼라곱 * 으로 가능 A로 행렬 지정 후 A*c 하면 됨 (c= 스케일값)

# 벡터화 연산 - 비교(논리) 연산
a=np.array([1,2,3,4])
b=np.array([4,2,3,1])
a==b
np.all(a==b)
# 벡터화 연산 - 지수 함수, 로그 함수 연산
c=np.arange(5)
np.exp(c)
10**c
np.log(c+1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [15]:
# 스칼라와 벡터/행렬의 곱셈
x=np.arange(10)
100*x
x=np.arange(12).reshape(3,4)
x
100*x


array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [16]:
# 브로드 캐스팅 - 크기가 다른 배열의 사칙 연산
x=np.arange(5)
y=np.ones_like(x)
x+y
x+1
# 더 차원이 높은 경우의 적용
x=np.vstack([range(7)[i:i+3]for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [48]:
# 차원 축소 연산
x=np.array([1,2,3,4])
np.sum(x)
x.sum()
y=np.array([1,3,2])
y.min()
y.max()
y.argmin() # 최소값의 위치
y.argmax()
y.mean()
np.all([True,True,False])
np.any([True,True,False])

# 연산의 대상이 2차원 이상인 경우 - axis 인수 활용 0은 열 연산, 1은 행 연산
x=np.array([[1,1],[2,3]])
x.sum()
x.sum(axis=0)
x.sum(axis=1)

array([2, 5])

In [18]:
# 연습문제
np.random.seed(0)
a=np.random.randint(1,1000,size=(5,6))
print(a)
a.max()
a.sum(axis=1)
for i in range(5):
    b1=a[i].max()
for j in range(6):
    b2=a[:,j].mean()
    b3=a[:,j].min()

[[685 560 630 193 836 764]
 [708 360  10 724 278 755]
 [805 600  71 473 601 397]
 [315 706 487 552  88 175]
 [601 850 678 538 846  73]]


In [19]:
# 정렬
a=np.array([[4, 3, 5, 7],
            [1,12,11, 9],
            [2,15, 1,14]])
np.sort(a) #axis=1과 동일(행 연산)
np.sort(a,axis=0)
b=np.array([42,38,12,25])
j=np.argsort(b)
b[j]

array([12, 25, 38, 42])

In [20]:
# 연습문제
a=np.array([[ 1, 2, 3, 4],
            [46,99,100,71],
            [81,59,90,100]])
print(a)
b=a[1]
j=np.argsort(b)
a[:,j]


[[  1   2   3   4]
 [ 46  99 100  71]
 [ 81  59  90 100]]


array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [21]:
# 행렬 곱연산 |
# @ - 지정해놓은 변수로 실행 c = a @ b 처럼   _____\ 이 둘은 (m, n) (n, k) shape여야 계산 가능
# numpy.dot() 두 벡터의 내적 계산 |          ㅡㅡㅡ/
# * - 스칼라곱 같은 shape 여야만 계산 가능(m, n)이 같아야 함 /예외로 (1, n) or (m, 1) 꼴일때는
#  shape가 달라도 가능
# ex) 
# [0, 1, 2] * [[-1 0 1] 이면 [[0 0 2]
#              [ 2 3 4]]      [0 3 8]] 이됨
#
# numpy.linalg.det(X) 행렬식 연산 X는 변수로 지정한 행렬 |
# numpy.linalg.inv(X) 역행렬 연산 |
# numpy.eye(n) n차원 단위행렬 == I |
# numpy.dot() 두 벡터의 내적 계산 |
# numpy.tril() 하삼각행렬 반환 |
# numpy.triu() 상삼각행렬 반환 |
#
# numpy.where(condition, x, y) - if 같은 느낌 (조건문, True값, False값) 으로 구성 |
#
# 행렬값 수정 |
# X =([]) 상태의 (예비)행렬존재시
# X = numpy.append(X, np.array[1, 2, 3], axis=0 or 1) 으로 1, 2, 3을 추가가능 
# axis=0이면 행 추가 axis =1 이면 열 추가 기존행렬과 모양 맞아야 함

### 기술 통계

In [22]:
# 간단한 통계량 계산
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])
len(x) # 데이터 개수
np.mean(x) # sample average
np.var(x)  # sample variance
np.std(x)  # sample standard variance
np.max(x)
np.min(x)
np.median(x)
np.percentile(x,0) # == min
np.percentile(x,25) # 1 quartile
np.percentile(x,50) # == median


5.0

### 난수 발생과 카운팅

In [23]:
# 시드 설정하기
np.random.seed(0) # 시드 고정

# 데이터 순서 바꾸기
x=np.arange(10)
np.random.shuffle(x) # 자체 변환 함수이니 조심

# 데이터 샘플링
# np.random.choice(a, size=None, replace=True, p=None)
# np.random.choice(a,(m,n),replace=False) 로도 사용함
# a : 데이터 or 정수 | 정수일때는 arange()로 작용됨
# size : 정수, 샘플 숫자
# replace : 불리언 True면 한 번 선택한 데이터 다시 선택 가능
# p : 각 데이터가 선택될 수 있는 확률

In [24]:
# 난수 생성
# rand : 0~1사이 균일분포 | randn : 표준 정규 분포 | randint : 균일 분포의 정수 난수
np.random.rand(10)
np.random.rand(3,5)
np.random.randn(4,4)

np.random.randint(10,size=10)
np.random.randint(1,10,size=(3,5))

array([[5, 5, 9, 5, 4],
       [8, 6, 6, 1, 2],
       [6, 4, 1, 6, 1]])

In [25]:
# 연습 문제

coin=np.array([1,0])
ex1=np.random.choice(coin,10,replace=True,p=[0.5,0.5])
print(ex1)
dice=np.array([1,2,3,4,5,6])
ex2=np.random.choice(dice,100,replace=True,p=[1/6,1/6,1/6,1/6,1/6,1/6])
print(ex2)



np.random.seed(0)
a=np.random.randn(250)
percentage=a/100
price=[10000+percentage[0]*10000]
for i in range(1,len(percentage)):
    Dprice=price[i-1]+price[i-1]*percentage[i]
    price.append(Dprice)
print(price)

[0 0 0 0 0 1 1 1 1 0]
[3 3 5 6 6 2 4 6 4 6 6 1 2 1 6 4 6 2 3 4 1 3 1 4 5 2 3 5 3 6 4 6 5 3 6 1 5
 3 5 2 2 6 4 4 4 2 3 4 3 3 5 2 3 5 6 1 1 3 4 1 6 2 2 1 1 6 2 4 3 1 3 3 6 6
 1 4 2 5 6 3 1 1 6 3 3 1 3 1 2 5 6 5 3 3 3 2 2 3 6 6]
[10176.405234596767, 10217.126853695665, 10317.125755097051, 10548.321524496083, 10745.317545953518, 10640.305934454434, 10741.398248726973, 10725.140368205562, 10714.070001464253, 10758.061812386894, 10773.55810880915, 10930.235110142823, 11013.418322778272, 11026.818901338936, 11075.762896183403, 11112.719873528811, 11278.752695617832, 11255.613402413064, 11290.85109259871, 11194.416414485922, 10908.624103482038, 10979.924899129086, 11074.839344564745, 10992.645760883175, 11242.151846339399, 11078.649848799967, 11083.719274707797, 11062.972342243344, 11232.543282795474, 11397.589642604074, 11415.249914346789, 11458.418111041767, 11356.69190814807, 11131.7389559244, 11093.010283665468, 11110.354090886578, 11247.043741862606, 11382.275929398731, 11338.1893222928, 

In [26]:
# 정수 데이터 카운팅
np.unique([11,11,2,2,34,34]) # 중복값 제거 후 정렬 추출
a=np.array(['a','b','b','c','a'])
index,count=np.unique(a,return_counts=True) 
index # 리스트 출력
count # 각 값의 개수 출력

np.bincount([1,1,2,2,2,3],minlength=6) # 값이 뽑히지 않은 경우 0으로 카운트 하고 싶을 때

array([0, 2, 3, 1, 0, 0], dtype=int64)